swagger:
  resourcePackage: examples.app.resources

# drop in the log file so we can transfer it with fetch-state easily
exportDirectory: /opt/app/log

server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /opt/app/log/access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /opt/app/log/access.%d.log.gz

logging:
  level: INFO
  loggers:
    examples.app: DEBUG
  appenders:
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /opt/app/log/application.log
      archivedLogFilenamePattern: //\opt/app/log/application-%d{yyyy-MM-dd}.log.gz
